### ISSUE TITLE
Use `extras` in settings to define engine specific settings

### ISSUE THREAD

**Issue by allendema** [allendema/searxng#6]
**Is your feature request related to a problem? Please describe.**

Use `extras` in settings to define engine specific settings.
```yaml
...
extras:
  key: value
  suffix: site:example.org
  something_else: true
```
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Move engine specific key value pairs to `extras` dict.
